parameters:
#    farmacia.example.class: knx\FarmaciaBundle\Example

services:
#    farmacia.example:
#        class: %farmacia.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
