<?php

namespace knx\HistoriaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HcRepository extends EntityRepository
{
	// Se consultan todas las historias clinicas del paciente por medio de su cedula ordenadas por fecha ASC
	public function findHistoriasPaciente($paciente) 
	{
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								hc
							 FROM
								HistoriaBundle:Hc hc
							 JOIN
								hc.factura f
							 JOIN
								f.paciente p
							 WHERE										
								p.id = :id
							 ORDER BY
								hc.fechaIngre DESC");

		$dql->setParameter('id', $paciente->getId());		
		return $dql->getResult();
	}

	// listar los diagnosticos que se encuentran asociados a la historia
	public function findHcDx($historia) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								c.id,c.nombre,c.codigo
							 FROM
								HistoriaBundle:HcDx hcdx
							 JOIN
								hcdx.cie c
							 WHERE
								hcdx.hc = :id 
							 ORDER BY
								c.nombre ASC");

		$dql->setParameter('id', $historia);
		return $dql->getResult();
	}

	// listar los examenes que se encuentran asociados a la historia
	public function findHcExamen($historia) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								e.id,e.nombre,e.codigo,e.tipo,hcEx.resultado
							 FROM
								HistoriaBundle:HcExamen hcEx
							 JOIN
								hcEx.examen e
							 WHERE
								hcEx.hc = :id
							 ORDER BY
								e.nombre ASC");

		$dql->setParameter('id', $historia);
		return $dql->getResult();
	}

	// listar los medicamentos que se encuentran asociados a la historia
	public function findHcLabora($historia) {
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
							"SELECT
								m.id,m.principioActivo,m.presentacion,m.concentracion,m.posologia,hcMe.estado
							 FROM
								HistoriaBundle:MedicamentoHistoria hcMe
							 JOIN
								hcMe.medicamento m
							 WHERE
								hcMe.hc = :id
							 ORDER BY
								m.principioActivo ASC");

		$dql->setParameter('id', $historia);
		return $dql->getResult();
	}
	
	// listar todas las historias que se encuentran en obsevacion o en internacion
	public function listHcUrgencias()
	{
		$em = $this->getEntityManager();
		$dql = $em->createQuery("SELECT 
									h
								 FROM 
									HistoriaBundle:Hc h
								 WHERE
									h.destino = '2'
								 ORDER BY
									h.updated DESC");
		return $dql->getResult();
	}
	
	
	// listar todas las historias que se encuentran en consulta externa
	public function listHcExternasPendientes($profesional)
	{
		$em = $this->getEntityManager();
		
		$dql = $em->createQuery("SELECT
									fc
                                                                        
								 FROM
									FacturacionBundle:FacturaCargo fc
								 JOIN
									fc.factura f
								 JOIN
									fc.cargo c
								 WHERE
									c.tipoCargo = :tipoCargo AND
									fc.estado = :estado AND								
									f.profesional = :profesional
                                                                 ORDER BY f.fecha ASC"          
                                                                            );
		
		$dql->setParameter('tipoCargo', 'CE');
		$dql->setParameter('estado', 'A');
		$dql->setParameter('profesional', $profesional);
		
		return $dql->getResult();
	}
	
	// listar todas las historias que apenas se an facturado como urgencias.
	public function listHcUrgenciasPendientes()
	{
		$em = $this->getEntityManager();
	
		$dql = $em->createQuery("SELECT
									fc
								 FROM
									FacturacionBundle:FacturaCargo fc
								 JOIN
									fc.factura f
								 JOIN
									fc.cargo c
								 WHERE
									c.tipoCargo = :tipoCargo AND 
									fc.estado = :estado");
	
		$dql->setParameter('tipoCargo', 'CU');
		$dql->setParameter('estado', 'A');
	
		return $dql->getResult();
	}
	
	
	// se realiza la consulta debida a que obtenga la factura cargo con sus debidos requerimientos
	public function closeFacturaCargoHc($factura, $tipoCargo)
	{
		$em = $this->getEntityManager();
	
		$dql = $em->createQuery("SELECT
									f.id AS factura, c.id AS cargo 
								 FROM
									FacturacionBundle:FacturaCargo fc
								 JOIN
									fc.factura f
								 JOIN
									fc.cargo c
								 WHERE
									f.id = :factura AND
									c.tipoCargo = :tipoCargo");
	
		$dql->setParameter('factura', $factura);
		$dql->setParameter('tipoCargo', $tipoCargo);

		$facturaCargo = $dql->getResult();
		if($facturaCargo)
			$facturaCargo = $em->getRepository('FacturacionBundle:FacturaCargo')->findOneBy(array('factura' => $facturaCargo[0]['factura'], 'cargo' => $facturaCargo[0]['cargo']));
		else 
			throw $this->createNotFoundException('Revise la factura y el tipo de cargo ya que hay informacion no disponible.');
	
		return $facturaCargo;
	}
}

/*
*/
