<?php

namespace knx\HistoriaBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * MedicamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicamentoRepository extends EntityRepository 
{
	function findByLaboratorioName($chart)
	{
		$em = $this->getEntityManager();
		$dql = $em->createQuery(
								"SELECT
									m.id, m.principioActivo, m.concentracion, m.presentacion
								 FROM
									HistoriaBundle:Medicamento m
								 WHERE
									m.principioActivo LIKE :laboratorio
								 ORDER BY
									m.principioActivo ASC"
		);
		$dql->setParameter('laboratorio', $chart.'%');
		return $dql->getResult();
	}
}
