imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:       ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Deprecated in 2.0; will be removed in 2.3 (used trusted_proxies instead)
    trusted_proxies: ~
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'ParametrizarBundle:Form:form_horizontal.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        mappings:
            gedmo_translatable:
                type:      annotation
                prefix:    Gedmo\Translatable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTranslatable
            gedmo_translator:
                type:      annotation
                prefix:    Gedmo\Translator\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTranslator
            gedmo_loggable:
                type:      annotation
                prefix:    Gedmo\Loggable\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoLoggable
            gedmo_tree:
                type:      annotation
                prefix:    Gedmo\Tree\Entity
                dir:       "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                is_bundle: false
                # el alias es opcional, por defecto se utiliza la clave de este mapeo
                alias:     GedmoTree
                
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    knx\UsuarioBundle\Entity\Usuario

vich_uploader:
    db_driver: orm
    mappings:
        product_image:
            uri_prefix: /images/products
            upload_destination: "%kernel.root_dir%/../web/images/products"
            
knp_paginator:
    page_range: 5  # número de páginas que se muestran en el paginador

    default_options:
        # los siguientes tres parámetros permiten "traducir" el paginador
        # puedes utilizar por ejemplo: 'pagina', 'ordenar' y 'direccion'
        page_name:           page
        sort_field_name:     sort
        sort_direction_name: direction

        # sólo incluir resultados diferentes (útil cuando haces consultas GROUP BY)
        distinct: true

    template:
        # estas opciones configuran la plantilla utilizada para la paginación
        # y para los controles que premiten reordenar los resultados
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable:   KnpPaginatorBundle:Pagination:sortable_link.html.twig
    
# Rastro de miga
white_october_breadcrumbs:
    separator:          ''
    separatorClass:     'separator'
    listId:             'wo-breadcrumbs'
    listClass:          ''
    itemClass:          
    locale:             
    translation_domain:
    
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: knx\UsuarioBundle\Entity\Usuario
    registration:
        form:
            type:     mi_user_registration
            
parameters:
    security.authentication.success_handler.class: knx\UsuarioBundle\Component\Security\Http\Authentication\AuthenticationSuccessHandler
    knx.directorio.uploads: %kernel.root_dir%/../web/uploads/
    knx.directorio.rips: %kernel.root_dir%/../web/rips/
    knx.directorio.conta: %kernel.root_dir%/../web/contabilidad/
    
services:
    security.authentication.success_handler:
        class: %security.authentication.success_handler.class%
        public: false
        arguments: ['@router', '@security.context']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
            
white_october_tcpdf:
    class: 'knx\FacturacionBundle\Pdf\KnxPdf'