homepage:
    pattern: /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: login, permanent: true }

login:
    pattern: /login
    defaults: { _controller: FOSUserBundle:Security:login }

ParametrizarBundle:
    resource: "@ParametrizarBundle/Resources/config/routing.yml"
    prefix:   /admin

HistoriaBundle:
    resource: "@HistoriaBundle/Resources/config/routing.yml"
    prefix:   /historia

FarmaciaBundle:
    resource: "@FarmaciaBundle/Resources/config/routing.yml"
    prefix:   /farmacia

FacturacionBundle:
    resource: "@FacturacionBundle/Resources/config/routing.yml"
    prefix:   /facturacion

UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /usuario

# FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /usuario/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /usuario/registrar

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /usuario/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /usuario/profile

# FOSJsRoutingBundle
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_bazinga_exposetranslation:
    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
    
login_check:
    pattern: /login_check

logout:
    pattern: /logout
