jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_referer: true
                success_handler: security.authentication.success_handler
            logout:       true
            anonymous:    true
            security:     true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/usuario/registrar, role: [ROLE_SUPER_ADMIN,ROLE_ADMIN] }
        - { path: ^/usuario/resetting, role: [ROLE_SUPER_ADMIN,ROLE_ADMIN] }
        - { path: ^/usuario/buscar/porcargo, role: [ROLE_USER] }
        - { path: ^/usuario/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: [ROLE_SUPER_ADMIN,ROLE_MEDICO,ROLE_AUXILIAR,ROLE_FACTURADOR,ROLE_ODONTOLOGO,ROLE_ESTADISTICO,ROLE_ADMIN] }
        - { path: ^/farmacia/, role: [ROLE_SUPER_ADMIN,ROLE_FARMACIA,ROLE_ADMIN,ROLE_FACTURADOR] }
        - { path: ^/usuario/, role: [ROLE_SUPER_ADMIN,ROLE_ADMIN] }
        - { path: ^/historia/, role: [ROLE_MEDICO,ROLE_AUXILIAR,ROLE_SUPER_ADMIN,ROLE_ODONTOLOGO,ROLE_ESTADISTICO] }
        - { path: ^/facturacion/, role: [ROLE_SUPER_ADMIN,ROLE_FACTURADOR,ROLE_ADMIN,ROLE_ESTADISTICO] }