parameters:
#    parametrizar.example.class: knx\ParametrizarBundle\Example

services:
#    parametrizar.example:
#        class: %parametrizar.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
